<?php

/**
 * Generated by Laravel to demonstrate version 7.0 features
 */

namespace App\Http\Controllers;

use App\Post;
use App\User;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;

class NewFeatureController extends Controller
{
    public function fluentStrings()
    {
        // Old way
        $string = Str::slug(trim(' the Rain in Spain falls Mainly on the plain '));

        // New way
        $string = Str::of(' the Rain in Spain falls Mainly on the plain ')
            ->trim(' ')
            ->slug('-');

        dd($string);
    }

    public function httpWrapper()
    {
        $response = Http::withHeaders(['X-Custom-Header' => 'a_value'])
            ->withToken('12345qwerty')
            ->timeout(3)
            ->get('https://jsonplaceholder.typicode.com/posts');

        if ($response->successful()) {
            $posts = $response->json();
            dd($posts);
        } else {
            dd($response->status());
        }
    }

    public function getUserPost(User $user, Post $post)
    {
        dd($post->toArray());
    }
}
